/**
 * Hardcoded diagram data for presets. When user selects a preset that has an entry here,
 * we return this data immediately (no LLM call). Nodes can include iconUrl for tech icons (Simple Icons CDN).
 */

import { TECH_ICON_URLS } from "./preset-icons";

export type PresetDiagram = {
  nodes: Array<{
    id: string;
    type: string;
    position: { x: number; y: number };
    data: { label: string; icon?: string; iconUrl?: string };
    parentId?: string;
  }>;
  edges: Array<{
    id: string;
    source: string;
    target: string;
    sourceHandle?: string;
    targetHandle?: string;
    data?: { label?: string };
  }>;
};

const edge = (
  id: string,
  source: string,
  target: string,
  label?: string
): PresetDiagram["edges"][0] => ({
  id,
  source,
  target,
  sourceHandle: "right",
  targetHandle: "left",
  ...(label && { data: { label } }),
});

/** Preset id -> diagram data. Keys must match DIAGRAM_PRESETS[].value */
export const PRESET_DIAGRAMS: Record<string, PresetDiagram> = {
  "auth0-flow": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User clicks Login" } },
      { id: "2", type: "rectangle", position: { x: 220, y: 80 }, data: { label: "Redirect to Auth0", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "3", type: "rectangle", position: { x: 440, y: 80 }, data: { label: "Login / Register", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "4", type: "rectangle", position: { x: 660, y: 80 }, data: { label: "Callback with tokens", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "5", type: "rectangle", position: { x: 880, y: 80 }, data: { label: "Validate token" } },
      { id: "6", type: "rectangle", position: { x: 1100, y: 80 }, data: { label: "Load session" } },
      { id: "7", type: "diamond", position: { x: 1320, y: 60 }, data: { label: "Profile complete?" } },
      { id: "8", type: "rectangle", position: { x: 1540, y: 20 }, data: { label: "Dashboard" } },
      { id: "9", type: "rectangle", position: { x: 1540, y: 100 }, data: { label: "Complete profile" } },
    ],
    edges: [
      edge("e1-2", "1", "2", "Click"),
      edge("e2-3", "2", "3", "Redirect"),
      edge("e3-4", "3", "4", "Callback"),
      edge("e4-5", "4", "5", "Validate"),
      edge("e5-6", "5", "6", "Session"),
      edge("e6-7", "6", "7", "Check"),
      edge("e7-8", "7", "8", "Yes"),
      edge("e7-9", "7", "9", "No"),
    ],
  },
  "stripe-payment": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 100 }, data: { label: "User selects product" } },
      { id: "2", type: "rectangle", position: { x: 240, y: 100 }, data: { label: "Cart" } },
      { id: "3", type: "rectangle", position: { x: 480, y: 100 }, data: { label: "Checkout" } },
      { id: "4", type: "rectangle", position: { x: 720, y: 100 }, data: { label: "Stripe payment", iconUrl: TECH_ICON_URLS.stripe } },
      { id: "5", type: "diamond", position: { x: 960, y: 80 }, data: { label: "Success?" } },
      { id: "6", type: "rectangle", position: { x: 1200, y: 40 }, data: { label: "Order confirmation" } },
      { id: "7", type: "rectangle", position: { x: 1200, y: 120 }, data: { label: "Failure / Retry" } },
      { id: "8", type: "rectangle", position: { x: 1440, y: 40 }, data: { label: "Email receipt" } },
    ],
    edges: [
      edge("e1-2", "1", "2", "Select"),
      edge("e2-3", "2", "3", "Cart"),
      edge("e3-4", "3", "4", "Checkout"),
      edge("e4-5", "4", "5", "Pay"),
      edge("e5-6", "5", "6", "Yes"),
      edge("e5-7", "5", "7", "No"),
      edge("e6-8", "6", "8", "Receipt"),
    ],
  },
  "support-call-flow": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 100 }, data: { label: "Call received" } },
      { id: "2", type: "rectangle", position: { x: 200, y: 100 }, data: { label: "IVR menu" } },
      { id: "3", type: "rectangle", position: { x: 400, y: 100 }, data: { label: "Route to queue" } },
      { id: "4", type: "rectangle", position: { x: 600, y: 100 }, data: { label: "Agent picks up" } },
      { id: "5", type: "rectangle", position: { x: 800, y: 100 }, data: { label: "Diagnose" } },
      { id: "6", type: "diamond", position: { x: 1000, y: 80 }, data: { label: "Resolve or Escalate?" } },
      { id: "7", type: "rectangle", position: { x: 1200, y: 40 }, data: { label: "Resolve" } },
      { id: "8", type: "rectangle", position: { x: 1200, y: 120 }, data: { label: "Escalate" } },
      { id: "9", type: "rectangle", position: { x: 1400, y: 80 }, data: { label: "Log ticket" } },
      { id: "10", type: "rectangle", position: { x: 1600, y: 80 }, data: { label: "Close" } },
    ],
    edges: [
      edge("e1-2", "1", "2", "Receive"),
      edge("e2-3", "2", "3", "Menu"),
      edge("e3-4", "3", "4", "Queue"),
      edge("e4-5", "4", "5", "Pick up"),
      edge("e5-6", "5", "6", "Check"),
      edge("e6-7", "6", "7", "Resolve"),
      edge("e6-8", "6", "8", "Escalate"),
      edge("e7-9", "7", "9", "Log"),
      edge("e8-9", "8", "9", "Log"),
      edge("e9-10", "9", "10", "Close"),
    ],
  },
  "ci-cd-pipeline": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 100 }, data: { label: "Developer push" } },
      { id: "2", type: "rectangle", position: { x: 220, y: 100 }, data: { label: "GitHub webhook", iconUrl: TECH_ICON_URLS.github } },
      { id: "3", type: "rectangle", position: { x: 440, y: 100 }, data: { label: "GitHub Actions", iconUrl: TECH_ICON_URLS.github } },
      { id: "4", type: "rectangle", position: { x: 660, y: 100 }, data: { label: "Build & test" } },
      { id: "5", type: "rectangle", position: { x: 880, y: 100 }, data: { label: "Docker → ECR", iconUrl: TECH_ICON_URLS.docker } },
      { id: "6", type: "rectangle", position: { x: 1100, y: 100 }, data: { label: "Deploy Staging", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "7", type: "diamond", position: { x: 1320, y: 80 }, data: { label: "E2E pass?" } },
      { id: "8", type: "rectangle", position: { x: 1540, y: 40 }, data: { label: "Deploy Prod", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "9", type: "rectangle", position: { x: 1540, y: 120 }, data: { label: "Rollback" } },
    ],
    edges: [
      edge("e1-2", "1", "2", "Push"),
      edge("e2-3", "2", "3", "Webhook"),
      edge("e3-4", "3", "4", "Lint & test"),
      edge("e4-5", "4", "5", "Build"),
      edge("e5-6", "5", "6", "Deploy"),
      edge("e6-7", "6", "7", "E2E"),
      edge("e7-8", "7", "8", "Yes"),
      edge("e7-9", "7", "9", "No"),
    ],
  },
  "ecommerce-sql": {
    nodes: [
      { id: "users", type: "document", position: { x: 0, y: 0 }, data: { label: "Users\nid, email, name" } },
      { id: "orders", type: "document", position: { x: 280, y: 0 }, data: { label: "Orders\nid, user_id, total" } },
      { id: "order_items", type: "document", position: { x: 560, y: 0 }, data: { label: "Order Items\nid, order_id, product_id" } },
      { id: "products", type: "document", position: { x: 560, y: 180 }, data: { label: "Products\nid, name, price" } },
      { id: "categories", type: "document", position: { x: 840, y: 180 }, data: { label: "Categories\nid, name" } },
      { id: "cart", type: "document", position: { x: 0, y: 180 }, data: { label: "Cart\nuser_id, product_id, qty" } },
      { id: "payments", type: "document", position: { x: 280, y: 180 }, data: { label: "Payments\nid, order_id, amount", iconUrl: TECH_ICON_URLS.stripe } },
    ],
    edges: [
      edge("e1", "users", "orders", "places"),
      edge("e2", "orders", "order_items", "contains"),
      edge("e3", "order_items", "products", "references"),
      edge("e4", "products", "categories", "belongs to"),
      edge("e5", "users", "cart", "has"),
      edge("e6", "cart", "products", "references"),
      edge("e7", "orders", "payments", "paid by"),
    ],
  },
  "twitter-data": {
    nodes: [
      { id: "users", type: "document", position: { x: 0, y: 80 }, data: { label: "Users\nid, handle, name" } },
      { id: "tweets", type: "document", position: { x: 240, y: 0 }, data: { label: "Tweets\nid, user_id, text" } },
      { id: "follows", type: "document", position: { x: 240, y: 160 }, data: { label: "Follows\nfollower_id, following_id" } },
      { id: "likes", type: "document", position: { x: 480, y: 40 }, data: { label: "Likes\nuser_id, tweet_id" } },
      { id: "replies", type: "document", position: { x: 480, y: 120 }, data: { label: "Replies\nid, tweet_id, parent_id" } },
      { id: "hashtags", type: "document", position: { x: 720, y: 80 }, data: { label: "Hashtags\nid, tag" } },
    ],
    edges: [
      edge("e1", "users", "tweets", "posts"),
      edge("e2", "users", "follows", "follows"),
      edge("e3", "users", "likes", "likes"),
      edge("e4", "tweets", "likes", "liked by"),
      edge("e5", "tweets", "replies", "replies"),
      edge("e6", "tweets", "hashtags", "tags"),
    ],
  },
  "oauth2-sequence": {
    nodes: [
      { id: "user", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User" } },
      { id: "app", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "App" } },
      { id: "auth", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "Auth Server", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "step1", type: "rectangle", position: { x: 0, y: 200 }, data: { label: "1. Request auth" } },
      { id: "step2", type: "rectangle", position: { x: 200, y: 260 }, data: { label: "2. Redirect to login" } },
      { id: "step3", type: "rectangle", position: { x: 400, y: 320 }, data: { label: "3. Return code" } },
      { id: "step4", type: "rectangle", position: { x: 200, y: 380 }, data: { label: "4. Exchange code for token" } },
    ],
    edges: [
      edge("e1", "user", "app", "Request auth"),
      edge("e2", "app", "auth", "Redirect"),
      edge("e3", "auth", "user", "Login"),
      edge("e4", "user", "app", "Return"),
      edge("e5", "app", "auth", "Code"),
      edge("e6", "app", "auth", "Token"),
    ],
  },
  "api-request-sequence": {
    nodes: [
      { id: "client", type: "rectangle", position: { x: 0, y: 60 }, data: { label: "Client" } },
      { id: "api", type: "rectangle", position: { x: 220, y: 60 }, data: { label: "API Gateway", iconUrl: TECH_ICON_URLS.nginx } },
      { id: "auth", type: "rectangle", position: { x: 440, y: 60 }, data: { label: "Auth", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "svc", type: "rectangle", position: { x: 660, y: 60 }, data: { label: "Service", iconUrl: TECH_ICON_URLS.nodedotjs } },
      { id: "db", type: "rectangle", position: { x: 880, y: 60 }, data: { label: "DB", iconUrl: TECH_ICON_URLS.postgresql } },
    ],
    edges: [
      edge("e1", "client", "api", "Request"),
      edge("e2", "api", "auth", "Validate"),
      edge("e3", "auth", "api", "JWT"),
      edge("e4", "api", "svc", "Forward"),
      edge("e5", "svc", "db", "Query"),
      edge("e6", "db", "svc", "Result"),
      edge("e7", "svc", "api", "Response"),
      edge("e8", "api", "client", "JSON"),
    ],
  },
  "order-approval-bpmn": {
    nodes: [
      { id: "start", type: "circle", position: { x: 0, y: 80 }, data: { label: "Start" } },
      { id: "t1", type: "rectangle", position: { x: 120, y: 80 }, data: { label: "Submit order" } },
      { id: "g1", type: "diamond", position: { x: 280, y: 60 }, data: { label: "Amount > 500?" } },
      { id: "t2", type: "rectangle", position: { x: 440, y: 40 }, data: { label: "Auto approve" } },
      { id: "t3", type: "rectangle", position: { x: 440, y: 120 }, data: { label: "Manager approval" } },
      { id: "join", type: "diamond", position: { x: 600, y: 80 }, data: { label: "Join" } },
      { id: "t4", type: "rectangle", position: { x: 720, y: 80 }, data: { label: "Fulfill order" } },
      { id: "end", type: "circle", position: { x: 860, y: 80 }, data: { label: "End" } },
    ],
    edges: [
      edge("e1", "start", "t1", "Start"),
      edge("e2", "t1", "g1", "Submit"),
      edge("e3", "g1", "t2", "Yes"),
      edge("e4", "g1", "t3", "No"),
      edge("e5", "t2", "join", "Approve"),
      edge("e6", "t3", "join", "Approve"),
      edge("e7", "join", "t4", "Merge"),
      edge("e8", "t4", "end", "Done"),
    ],
  },
  "support-ticket-bpmn": {
    nodes: [
      { id: "start", type: "circle", position: { x: 0, y: 80 }, data: { label: "Start" } },
      { id: "t1", type: "rectangle", position: { x: 100, y: 80 }, data: { label: "Create ticket" } },
      { id: "t2", type: "rectangle", position: { x: 260, y: 80 }, data: { label: "Assign agent" } },
      { id: "g1", type: "diamond", position: { x: 420, y: 60 }, data: { label: "Resolved?" } },
      { id: "t3", type: "rectangle", position: { x: 580, y: 40 }, data: { label: "Close ticket" } },
      { id: "t4", type: "rectangle", position: { x: 580, y: 120 }, data: { label: "Escalate" } },
      { id: "end", type: "circle", position: { x: 740, y: 80 }, data: { label: "End" } },
    ],
    edges: [
      edge("e1", "start", "t1", "Create"),
      edge("e2", "t1", "t2", "Assign"),
      edge("e3", "t2", "g1", "Work"),
      edge("e4", "g1", "t3", "Yes"),
      edge("e5", "g1", "t4", "No"),
      edge("e6", "t3", "end", "Close"),
      edge("e7", "t4", "t2", "Reassign"),
    ],
  },
  "simple-3-tier": {
    nodes: [
      { id: "user", type: "rectangle", position: { x: 0, y: 100 }, data: { label: "User" } },
      { id: "web", type: "rectangle", position: { x: 220, y: 60 }, data: { label: "Web Server" } },
      { id: "api", type: "rectangle", position: { x: 440, y: 100 }, data: { label: "API Server" } },
      { id: "db", type: "rectangle", position: { x: 660, y: 100 }, data: { label: "Database" } },
    ],
    edges: [
      edge("e1", "user", "web", "Request"),
      edge("e2", "web", "api", "API call"),
      edge("e3", "api", "db", "Query"),
    ],
  },
  "serverless-api": {
    nodes: [
      { id: "client", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "Client" } },
      { id: "cf", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "CloudFront", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "api", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "API Gateway", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "lambda", type: "rectangle", position: { x: 600, y: 80 }, data: { label: "Lambda", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "dynamo", type: "rectangle", position: { x: 800, y: 80 }, data: { label: "DynamoDB", iconUrl: TECH_ICON_URLS.amazonaws } },
    ],
    edges: [
      edge("e1", "client", "cf", "Request"),
      edge("e2", "cf", "api", "Proxy"),
      edge("e3", "api", "lambda", "Invoke"),
      edge("e4", "lambda", "dynamo", "Read/Write"),
    ],
  },
  "puppy-training": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 100 }, data: { label: "Sign up" } },
      { id: "2", type: "diamond", position: { x: 200, y: 80 }, data: { label: "Program?" } },
      { id: "3a", type: "rectangle", position: { x: 400, y: 40 }, data: { label: "Self-led" } },
      { id: "3b", type: "rectangle", position: { x: 400, y: 120 }, data: { label: "Trainer-led" } },
      { id: "4", type: "rectangle", position: { x: 600, y: 80 }, data: { label: "Onboarding" } },
      { id: "5", type: "rectangle", position: { x: 800, y: 80 }, data: { label: "Daily lessons" } },
      { id: "6", type: "rectangle", position: { x: 1000, y: 80 }, data: { label: "Progress" } },
      { id: "7", type: "rectangle", position: { x: 1200, y: 80 }, data: { label: "Certificate" } },
    ],
    edges: [
      edge("e1", "1", "2", "Sign up"),
      edge("e2", "2", "3a", "Self"),
      edge("e3", "2", "3b", "Trainer"),
      edge("e4", "3a", "4", "Join"),
      edge("e5", "3b", "4", "Join"),
      edge("e6", "4", "5", "Lessons"),
      edge("e7", "5", "6", "Track"),
      edge("e8", "6", "7", "Complete"),
    ],
  },
  // —— Presets that were missing (seed fills nodes/edges from these) ——
  "ecommerce-full-scale": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User / Browser", iconUrl: TECH_ICON_URLS.react } },
      { id: "2", type: "rectangle", position: { x: 200, y: 40 }, data: { label: "CDN / CloudFront", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "3", type: "rectangle", position: { x: 200, y: 120 }, data: { label: "Next.js SSR+CSR", iconUrl: TECH_ICON_URLS.nextdotjs } },
      { id: "4", type: "rectangle", position: { x: 420, y: 80 }, data: { label: "API Gateway", iconUrl: TECH_ICON_URLS.nginx } },
      { id: "5", type: "rectangle", position: { x: 620, y: 20 }, data: { label: "Auth (OAuth2/JWT)", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "6", type: "rectangle", position: { x: 620, y: 80 }, data: { label: "User Service" } },
      { id: "7", type: "rectangle", position: { x: 620, y: 140 }, data: { label: "Product Catalog" } },
      { id: "8", type: "rectangle", position: { x: 840, y: 20 }, data: { label: "Order Service" } },
      { id: "9", type: "rectangle", position: { x: 840, y: 80 }, data: { label: "Payment (Stripe)", iconUrl: TECH_ICON_URLS.stripe } },
      { id: "10", type: "rectangle", position: { x: 840, y: 140 }, data: { label: "Kafka", iconUrl: TECH_ICON_URLS.kafka } },
      { id: "11", type: "rectangle", position: { x: 1060, y: 60 }, data: { label: "PostgreSQL", iconUrl: TECH_ICON_URLS.postgresql } },
      { id: "12", type: "rectangle", position: { x: 1060, y: 120 }, data: { label: "Redis", iconUrl: TECH_ICON_URLS.redis } },
      { id: "13", type: "rectangle", position: { x: 1280, y: 80 }, data: { label: "S3", iconUrl: TECH_ICON_URLS.amazonaws } },
    ],
    edges: [
      edge("e1", "1", "2", "Static"),
      edge("e2", "1", "3", "App"),
      edge("e3", "2", "4", "Cache"),
      edge("e4", "3", "4", "API"),
      edge("e5", "4", "5", "Auth"),
      edge("e6", "4", "6", "User"),
      edge("e7", "4", "7", "Catalog"),
      edge("e8", "6", "8", "Order"),
      edge("e9", "7", "8", "Items"),
      edge("e10", "8", "9", "Pay"),
      edge("e11", "8", "10", "Events"),
      edge("e12", "9", "11", "Store"),
      edge("e13", "6", "12", "Cache"),
      edge("e14", "8", "13", "Assets"),
    ],
  },
  "ecommerce-mern-aws": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User" } },
      { id: "2", type: "rectangle", position: { x: 180, y: 40 }, data: { label: "CloudFront + S3", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "3", type: "rectangle", position: { x: 180, y: 120 }, data: { label: "React SPA", iconUrl: TECH_ICON_URLS.react } },
      { id: "4", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "ALB", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "5", type: "rectangle", position: { x: 580, y: 80 }, data: { label: "Node.js/Express", iconUrl: TECH_ICON_URLS.nodedotjs } },
      { id: "6", type: "rectangle", position: { x: 780, y: 40 }, data: { label: "MongoDB Atlas", iconUrl: TECH_ICON_URLS.mongodb } },
      { id: "7", type: "rectangle", position: { x: 780, y: 120 }, data: { label: "Redis", iconUrl: TECH_ICON_URLS.redis } },
      { id: "8", type: "rectangle", position: { x: 980, y: 80 }, data: { label: "AWS SQS / SNS", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "9", type: "rectangle", position: { x: 1180, y: 80 }, data: { label: "Stripe", iconUrl: TECH_ICON_URLS.stripe } },
    ],
    edges: [
      edge("e1", "1", "2", "Static"),
      edge("e2", "1", "3", "SPA"),
      edge("e3", "2", "4", "HTTPS"),
      edge("e4", "3", "4", "API"),
      edge("e5", "4", "5", "Backend"),
      edge("e6", "5", "6", "DB"),
      edge("e7", "5", "7", "Cache"),
      edge("e8", "5", "8", "Queue"),
      edge("e9", "5", "9", "Pay"),
    ],
  },
  "auth-oauth2-jwt-full": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User clicks Login" } },
      { id: "2", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "Redirect to IdP", iconUrl: TECH_ICON_URLS.auth0 } },
      { id: "3", type: "rectangle", position: { x: 420, y: 80 }, data: { label: "Login/Register" } },
      { id: "4", type: "rectangle", position: { x: 640, y: 80 }, data: { label: "Authorization code" } },
      { id: "5", type: "rectangle", position: { x: 860, y: 40 }, data: { label: "Exchange code → tokens" } },
      { id: "6", type: "rectangle", position: { x: 860, y: 120 }, data: { label: "Store (httpOnly cookie)" } },
      { id: "7", type: "diamond", position: { x: 1080, y: 60 }, data: { label: "Token valid?" } },
      { id: "8", type: "rectangle", position: { x: 1300, y: 20 }, data: { label: "API request" } },
      { id: "9", type: "rectangle", position: { x: 1300, y: 100 }, data: { label: "Refresh token" } },
    ],
    edges: [
      edge("e1", "1", "2", "Login"),
      edge("e2", "2", "3", "Redirect"),
      edge("e3", "3", "4", "Code"),
      edge("e4", "4", "5", "Exchange"),
      edge("e5", "5", "6", "Store"),
      edge("e6", "6", "7", "Check"),
      edge("e7", "7", "8", "Yes"),
      edge("e8", "7", "9", "No"),
    ],
  },
  "stripe-payment-advanced": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "Checkout" } },
      { id: "2", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "Create PaymentIntent", iconUrl: TECH_ICON_URLS.stripe } },
      { id: "3", type: "rectangle", position: { x: 420, y: 80 }, data: { label: "Stripe.js confirm" } },
      { id: "4", type: "diamond", position: { x: 640, y: 60 }, data: { label: "Webhook received?" } },
      { id: "5", type: "rectangle", position: { x: 860, y: 20 }, data: { label: "Verify signature" } },
      { id: "6", type: "diamond", position: { x: 860, y: 100 }, data: { label: "Duplicate?" } },
      { id: "7", type: "rectangle", position: { x: 1080, y: 40 }, data: { label: "Fulfill order" } },
      { id: "8", type: "rectangle", position: { x: 1080, y: 120 }, data: { label: "Idempotent skip" } },
    ],
    edges: [
      edge("e1", "1", "2", "Checkout"),
      edge("e2", "2", "3", "PaymentIntent"),
      edge("e3", "3", "4", "Confirm"),
      edge("e4", "4", "5", "Yes"),
      edge("e5", "5", "6", "Verify"),
      edge("e6", "6", "7", "No"),
      edge("e7", "6", "8", "Yes"),
    ],
  },
  "kafka-event-flow": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 120 }, data: { label: "Order Service" } },
      { id: "2", type: "rectangle", position: { x: 0, y: 200 }, data: { label: "Payment Service" } },
      { id: "3", type: "rectangle", position: { x: 0, y: 280 }, data: { label: "Inventory Service" } },
      { id: "4", type: "rectangle", position: { x: 280, y: 200 }, data: { label: "Kafka", iconUrl: TECH_ICON_URLS.kafka } },
      { id: "5", type: "rectangle", position: { x: 520, y: 80 }, data: { label: "order_created" } },
      { id: "6", type: "rectangle", position: { x: 520, y: 160 }, data: { label: "payment_completed" } },
      { id: "7", type: "rectangle", position: { x: 520, y: 240 }, data: { label: "inventory_updated" } },
      { id: "8", type: "rectangle", position: { x: 760, y: 120 }, data: { label: "Notification Service" } },
      { id: "9", type: "rectangle", position: { x: 760, y: 200 }, data: { label: "Analytics Service" } },
    ],
    edges: [
      edge("e1", "1", "4", "Publish"),
      edge("e2", "2", "4", "Publish"),
      edge("e3", "3", "4", "Publish"),
      edge("e4", "4", "5", "order_created"),
      edge("e5", "4", "6", "payment_completed"),
      edge("e6", "4", "7", "inventory_updated"),
      edge("e7", "5", "8", "Notify"),
      edge("e8", "6", "8", "Notify"),
      edge("e9", "6", "9", "Analytics"),
    ],
  },
  "product-microservices": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "CDN", iconUrl: TECH_ICON_URLS.amazonaws } },
      { id: "2", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "Frontend" } },
      { id: "3", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "API Gateway" } },
      { id: "4", type: "rectangle", position: { x: 620, y: 20 }, data: { label: "Product service" } },
      { id: "5", type: "rectangle", position: { x: 620, y: 80 }, data: { label: "Inventory" } },
      { id: "6", type: "rectangle", position: { x: 620, y: 140 }, data: { label: "Reviews" } },
      { id: "7", type: "rectangle", position: { x: 840, y: 80 }, data: { label: "Kafka", iconUrl: TECH_ICON_URLS.kafka } },
    ],
    edges: [
      edge("e1", "1", "2", "Request"),
      edge("e2", "2", "3", "Route"),
      edge("e3", "3", "4", "Product"),
      edge("e4", "3", "5", "Stock"),
      edge("e5", "3", "6", "Reviews"),
      edge("e6", "4", "7", "Events"),
      edge("e7", "5", "7", "Events"),
      edge("e8", "6", "7", "Events"),
    ],
  },
  "ci-cd-advanced": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "Developer push" } },
      { id: "2", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "GitHub Actions", iconUrl: TECH_ICON_URLS.github } },
      { id: "3", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "Lint, test, build" } },
      { id: "4", type: "rectangle", position: { x: 600, y: 80 }, data: { label: "Docker → ECR", iconUrl: TECH_ICON_URLS.docker } },
      { id: "5", type: "rectangle", position: { x: 800, y: 40 }, data: { label: "Deploy Staging", iconUrl: TECH_ICON_URLS.kubernetes } },
      { id: "6", type: "diamond", position: { x: 1000, y: 60 }, data: { label: "E2E pass?" } },
      { id: "7", type: "rectangle", position: { x: 1200, y: 20 }, data: { label: "Deploy Prod" } },
      { id: "8", type: "rectangle", position: { x: 1200, y: 100 }, data: { label: "Rollback" } },
    ],
    edges: [
      edge("e1", "1", "2", "Push"),
      edge("e2", "2", "3", "Actions"),
      edge("e3", "3", "4", "Build"),
      edge("e4", "4", "5", "Image"),
      edge("e5", "5", "6", "Deploy"),
      edge("e6", "6", "7", "Yes"),
      edge("e7", "6", "8", "No"),
    ],
  },
  "chatbot-arch": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "User" } },
      { id: "2", type: "rectangle", position: { x: 200, y: 80 }, data: { label: "Chat UI" } },
      { id: "3", type: "rectangle", position: { x: 400, y: 80 }, data: { label: "API Gateway" } },
      { id: "4", type: "rectangle", position: { x: 600, y: 40 }, data: { label: "Auth" } },
      { id: "5", type: "rectangle", position: { x: 600, y: 120 }, data: { label: "Chat service" } },
      { id: "6", type: "rectangle", position: { x: 800, y: 80 }, data: { label: "LLM (OpenAI)" } },
      { id: "7", type: "rectangle", position: { x: 1000, y: 80 }, data: { label: "Vector DB (RAG)" } },
      { id: "8", type: "rectangle", position: { x: 1200, y: 80 }, data: { label: "Redis", iconUrl: TECH_ICON_URLS.redis } },
    ],
    edges: [
      edge("e1", "1", "2", "Message"),
      edge("e2", "2", "3", "API"),
      edge("e3", "3", "4", "Auth"),
      edge("e4", "3", "5", "Chat"),
      edge("e5", "5", "6", "LLM"),
      edge("e6", "6", "7", "RAG"),
      edge("e7", "5", "8", "Session"),
    ],
  },
  "gig-marketplace": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "Buyers / Sellers" } },
      { id: "2", type: "rectangle", position: { x: 220, y: 80 }, data: { label: "Frontend" } },
      { id: "3", type: "rectangle", position: { x: 440, y: 80 }, data: { label: "API Gateway" } },
      { id: "4", type: "rectangle", position: { x: 660, y: 40 }, data: { label: "Search" } },
      { id: "5", type: "rectangle", position: { x: 660, y: 120 }, data: { label: "Order" } },
      { id: "6", type: "rectangle", position: { x: 660, y: 200 }, data: { label: "Payment" } },
      { id: "7", type: "rectangle", position: { x: 880, y: 80 }, data: { label: "Notification" } },
      { id: "8", type: "rectangle", position: { x: 1100, y: 80 }, data: { label: "DB" } },
    ],
    edges: [
      edge("e1", "1", "2", "Browse"),
      edge("e2", "2", "3", "API"),
      edge("e3", "3", "4", "Search"),
      edge("e4", "3", "5", "Order"),
      edge("e5", "3", "6", "Pay"),
      edge("e6", "4", "7", "Notify"),
      edge("e7", "5", "7", "Notify"),
      edge("e8", "6", "8", "Persist"),
    ],
  },
  "saas-multi-tenant": {
    nodes: [
      { id: "1", type: "rectangle", position: { x: 0, y: 80 }, data: { label: "Tenants / Users" } },
      { id: "2", type: "rectangle", position: { x: 220, y: 80 }, data: { label: "Next.js", iconUrl: TECH_ICON_URLS.nextdotjs } },
      { id: "3", type: "rectangle", position: { x: 440, y: 80 }, data: { label: "API Gateway" } },
      { id: "4", type: "rectangle", position: { x: 660, y: 20 }, data: { label: "Auth" } },
      { id: "5", type: "rectangle", position: { x: 660, y: 80 }, data: { label: "Billing", iconUrl: TECH_ICON_URLS.stripe } },
      { id: "6", type: "rectangle", position: { x: 660, y: 140 }, data: { label: "Core" } },
      { id: "7", type: "rectangle", position: { x: 880, y: 60 }, data: { label: "PostgreSQL", iconUrl: TECH_ICON_URLS.postgresql } },
      { id: "8", type: "rectangle", position: { x: 880, y: 120 }, data: { label: "Redis", iconUrl: TECH_ICON_URLS.redis } },
    ],
    edges: [
      edge("e1", "1", "2", "Request"),
      edge("e2", "2", "3", "API"),
      edge("e3", "3", "4", "Auth"),
      edge("e4", "3", "5", "Billing"),
      edge("e5", "3", "6", "Core"),
      edge("e6", "4", "7", "DB"),
      edge("e7", "5", "7", "DB"),
      edge("e8", "6", "8", "Cache"),
    ],
  },
};

/** Returns diagram for preset if we have hardcoded data; otherwise null */
export function getPresetDiagram(presetValue: string): PresetDiagram | null {
  return PRESET_DIAGRAMS[presetValue] ?? null;
}
