/**
 * Hardcoded diagram data for the Our website template.
 * Loaded from DB when user clicks the template. Enables instant load without AI generation.
 */

/** Our website: AI Diagram App - Full architecture with groups (Frontend, Auth, API, AI, Data) */
export const OUR_WEBSITE_TEMPLATE = {
  nodes: [
    {
      id: "user",
      data: { icon: "lucide:users", label: "User", iconUrl: "https://cdn.simpleicons.org/user/3b82f6" },
      type: "actor",
      position: { x: 80, y: 326.952380952381 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "frontend-group",
      data: { label: "Frontend" },
      type: "group",
      style: { width: 540, height: 736 },
      width: 540,
      height: 736,
      position: { x: 380, y: 98.952380952381 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "nextjs",
      data: {
        icon: "si:Next.js",
        label: "Next.js 16.1",
        iconUrl: "https://cdn.simpleicons.org/nextdotjs/000000",
        subtitle: "App Router, React 19",
        annotation: "v16.1",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 80, y: 149.714285714286 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "reactflow",
      data: {
        icon: "si:React",
        label: "React Flow",
        iconUrl: "https://cdn.simpleicons.org/react/61DAFB",
        subtitle: "@xyflow/react",
        annotation: "v12",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 492 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "excalidraw",
      data: {
        icon: "lucide:code",
        label: "Excalidraw",
        iconUrl: "https://cdn.simpleicons.org/excalidraw/6965DB",
        subtitle: "@excalidraw/excalidraw",
        annotation: "v0.18",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 584 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "drawio",
      data: {
        icon: "lucide:box",
        label: "Draw.io",
        iconUrl: "https://cdn.simpleicons.org/diagramsdotnet/F08705",
        subtitle: "react-drawio",
        annotation: "v1",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "zustand",
      data: {
        icon: "lucide:box",
        label: "Zustand",
        iconUrl: "https://cdn.simpleicons.org/zustand/443E38",
        subtitle: "State management",
        annotation: "v5",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 308 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "tailwind",
      data: {
        icon: "lucide:code",
        label: "Tailwind CSS",
        iconUrl: "https://cdn.simpleicons.org/tailwindcss/06B6D4",
        subtitle: "Styling",
        annotation: "v4",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "radix",
      data: {
        icon: "lucide:box",
        label: "Radix UI",
        iconUrl: "https://cdn.simpleicons.org/radixui/161618",
        subtitle: "Component library",
      },
      type: "service",
      extent: "parent",
      parentId: "frontend-group",
      position: { x: 300, y: 400 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "auth-group",
      data: { label: "Auth" },
      type: "group",
      style: { width: 320, height: 276 },
      width: 320,
      height: 276,
      position: { x: 984, y: 328.952380952381 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "clerk",
      data: {
        icon: "lucide:shield",
        label: "Clerk Auth",
        iconUrl: "https://cdn.simpleicons.org/clerk/6C47FF",
        subtitle: "@clerk/nextjs",
        annotation: "v6",
      },
      type: "service",
      extent: "parent",
      parentId: "auth-group",
      position: { x: 80, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-group",
      data: { label: "API Routes" },
      type: "group",
      style: { width: 500, height: 460 },
      width: 500,
      height: 460,
      position: { x: 1368, y: 302.666666666667 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-generate",
      data: {
        icon: "lucide:code",
        label: "/api/diagrams/generate",
        iconUrl: "https://cdn.simpleicons.org/vercel/000000",
        subtitle: "Vercel AI SDK + OpenAI",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 80, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-langchain",
      data: {
        icon: "si:LangChain",
        label: "/api/diagrams/langchain",
        iconUrl: "https://cdn.simpleicons.org/langchain/1C3C3C",
        subtitle: "LangChain streaming",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 260, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-drawio",
      data: {
        icon: "si:LangChain",
        label: "/api/generate-drawio",
        iconUrl: "https://cdn.simpleicons.org/langchain/1C3C3C",
        subtitle: "LangChain ChatOpenAI",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 80, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-excalidraw",
      data: {
        icon: "si:LangChain",
        label: "/api/generate-excalidraw",
        iconUrl: "https://cdn.simpleicons.org/langchain/1C3C3C",
        subtitle: "LangChain ChatOpenAI",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 260, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-upload",
      data: {
        icon: "si:AWS",
        label: "/api/upload",
        iconUrl: "https://cdn.simpleicons.org/amazonaws/FF9900",
        subtitle: "S3 presigned URLs",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 80, y: 308 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "api-crud",
      data: {
        icon: "lucide:database",
        label: "/api/presets, /documents",
        iconUrl: "https://cdn.simpleicons.org/postgresql/4169E1",
        subtitle: "CRUD operations",
      },
      type: "service",
      extent: "parent",
      parentId: "api-group",
      position: { x: 260, y: 308 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "ai-group",
      data: { label: "AI Stack" },
      type: "group",
      style: { width: 500, height: 368 },
      width: 500,
      height: 368,
      position: { x: 1932, y: 12 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "vercel-ai",
      data: {
        icon: "lucide:cpu",
        label: "Vercel AI SDK",
        iconUrl: "https://cdn.simpleicons.org/vercel/000000",
        subtitle: "ai v4",
        annotation: "v4",
      },
      type: "service",
      extent: "parent",
      parentId: "ai-group",
      position: { x: 80, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "langchain-core",
      data: {
        icon: "si:LangChain",
        label: "LangChain",
        iconUrl: "https://cdn.simpleicons.org/langchain/1C3C3C",
        subtitle: "@langchain/core, @langchain/openai",
        annotation: "v1.2",
      },
      type: "service",
      extent: "parent",
      parentId: "ai-group",
      position: { x: 80, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "openai",
      data: {
        icon: "si:OpenAI",
        label: "OpenAI",
        iconUrl: "https://cdn.simpleicons.org/openai/412991",
        subtitle: "GPT-4o, GPT-4o-mini",
      },
      type: "service",
      extent: "parent",
      parentId: "ai-group",
      position: { x: 260, y: 136 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "data-group",
      data: { label: "Data & Storage" },
      type: "group",
      style: { width: 680, height: 368 },
      width: 680,
      height: 368,
      position: { x: 1932, y: 440 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "neon",
      data: {
        icon: "lucide:database",
        label: "Neon PostgreSQL",
        iconUrl: "https://cdn.simpleicons.org/postgresql/4169E1",
        subtitle: "@neondatabase/serverless",
      },
      type: "service",
      extent: "parent",
      parentId: "data-group",
      position: { x: 80, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "drizzle",
      data: {
        icon: "lucide:database",
        label: "Drizzle ORM",
        iconUrl: "https://cdn.simpleicons.org/drizzle/C5F74F",
        subtitle: "drizzle-orm",
        annotation: "v0.38",
      },
      type: "service",
      extent: "parent",
      parentId: "data-group",
      position: { x: 260, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "s3",
      data: {
        icon: "si:AWS",
        label: "AWS S3",
        iconUrl: "https://cdn.simpleicons.org/amazonaws/FF9900",
        subtitle: "@aws-sdk/client-s3",
        annotation: "v3",
      },
      type: "service",
      extent: "parent",
      parentId: "data-group",
      position: { x: 80, y: 124 },
      sourcePosition: "right",
      targetPosition: "left",
    },
    {
      id: "tables",
      data: {
        icon: "lucide:database",
        label: "Database Tables",
        iconUrl: "https://cdn.simpleicons.org/postgresql/4169E1",
        subtitle: "documents, diagram_presets, user_files",
      },
      type: "service",
      extent: "parent",
      parentId: "data-group",
      position: { x: 440, y: 216 },
      sourcePosition: "right",
      targetPosition: "left",
    },
  ],
  edges: [
    { id: "e-0-user-nextjs", data: { strokeColor: "#3b82f6" }, source: "user", target: "nextjs", sourceHandle: "right", targetHandle: "left" },
    { id: "e-1-nextjs-clerk", data: { label: "Auth", strokeColor: "#8b5cf6" }, source: "nextjs", target: "clerk", sourceHandle: "right", targetHandle: "left" },
    { id: "e-2-clerk-api-generate", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-generate", sourceHandle: "right", targetHandle: "left" },
    { id: "e-3-clerk-api-langchain", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-langchain", sourceHandle: "right", targetHandle: "left" },
    { id: "e-4-clerk-api-drawio", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-drawio", sourceHandle: "right", targetHandle: "left" },
    { id: "e-5-clerk-api-excalidraw", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-excalidraw", sourceHandle: "right", targetHandle: "left" },
    { id: "e-6-clerk-api-upload", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-upload", sourceHandle: "right", targetHandle: "left" },
    { id: "e-7-clerk-api-crud", data: { strokeColor: "#3b82f6" }, source: "clerk", target: "api-crud", sourceHandle: "right", targetHandle: "left" },
    { id: "e-8-api-generate-vercel-ai", data: { strokeColor: "#22c55e" }, source: "api-generate", target: "vercel-ai", sourceHandle: "right", targetHandle: "left" },
    { id: "e-9-api-langchain-langchain-core", data: { strokeColor: "#22c55e" }, source: "api-langchain", target: "langchain-core", sourceHandle: "right", targetHandle: "left" },
    { id: "e-10-api-drawio-langchain-core", data: { strokeColor: "#22c55e" }, source: "api-drawio", target: "langchain-core", sourceHandle: "right", targetHandle: "left" },
    { id: "e-11-api-excalidraw-langchain-core", data: { strokeColor: "#22c55e" }, source: "api-excalidraw", target: "langchain-core", sourceHandle: "right", targetHandle: "left" },
    { id: "e-12-vercel-ai-openai", data: { label: "LLM", strokeColor: "#ec4899" }, source: "vercel-ai", target: "openai", sourceHandle: "right", targetHandle: "left" },
    { id: "e-13-langchain-core-openai", data: { label: "LLM", strokeColor: "#ec4899" }, source: "langchain-core", target: "openai", sourceHandle: "right", targetHandle: "left" },
    { id: "e-14-api-crud-neon", data: { strokeColor: "#eab308" }, source: "api-crud", target: "neon", sourceHandle: "right", targetHandle: "left" },
    { id: "e-15-neon-drizzle", data: { label: "ORM", strokeColor: "#eab308" }, source: "neon", target: "drizzle", sourceHandle: "right", targetHandle: "left" },
    { id: "e-16-drizzle-tables", data: { strokeColor: "#eab308" }, source: "drizzle", target: "tables", sourceHandle: "right", targetHandle: "left" },
    { id: "e-17-api-upload-s3", data: { label: "Presigned URLs", strokeColor: "#f97316" }, source: "api-upload", target: "s3", sourceHandle: "right", targetHandle: "left" },
    { id: "e-18-nextjs-reactflow", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "reactflow", sourceHandle: "right", targetHandle: "left" },
    { id: "e-19-nextjs-excalidraw", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "excalidraw", sourceHandle: "right", targetHandle: "left" },
    { id: "e-20-nextjs-drawio", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "drawio", sourceHandle: "right", targetHandle: "left" },
    { id: "e-21-nextjs-tailwind", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "tailwind", sourceHandle: "right", targetHandle: "left" },
    { id: "e-22-nextjs-zustand", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "zustand", sourceHandle: "right", targetHandle: "left" },
    { id: "e-23-nextjs-radix", data: { strokeColor: "#14b8a6" }, source: "nextjs", target: "radix", sourceHandle: "right", targetHandle: "left" },
  ],
  layoutDirection: "horizontal",
  groups: [],
};

/** Map preset/template name -> diagram data */
export const TEMPLATE_DIAGRAM_DATA: Record<string, { nodes: unknown[]; edges: unknown[]; layoutDirection?: string }> = {
  "template-our-website-ai-diagram-app": OUR_WEBSITE_TEMPLATE,
};
